# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'MiJo' do
pod 'react-native-image-crop-picker', :path => '../node_modules/react-native-image-crop-picker/ios'

end

target 'MiJoTests' do

end
